vmagent_scrape_config:
  global:
    scrape_interval: 30s
  scrape_configs:
    - job_name: mysql-exporter
      static_configs:
        - targets: ["mysql-exporter.internal:9104"]
    - job_name: kafka-exporter
      metrics_path: /metrics
      static_configs:
        - targets:
            - 172.16.1.104:9308
            - 172.16.1.99:9308
            - 172.16.1.105:9308
    - job_name: elasticsearch-exporter
      static_configs:
        - targets: ["elasticsearch-exporter.internal:9114"]